version: '3.5'
services:
    # Service for traefik
    traefik:
        image: traefik:2.0
        command: 
            # Entrypoint by name web is created with port 80. Traefik will listen on this port for all application
            - --entrypoints.web.address=:80
            # Log level of traefik container set to INFO
            - --log.level=INFO
            # A docker provider is set for treafik.
            - --providers.docker
            # Traefik won't register all the container on given docker instance
            - --providers.docker.exposedbydefault=false
            # Run traefik API on insecure protocol
            - --api.insecure
        ports:
            # Traefik port 80 mapped on host OS port 9090
            - "9090:80"
            # Traefik api port 8080 mapped on host OS port 8080, This will show dashboard of Traefik
            - "8080:8080"
        volumes: 
            # Volume mapping of docker.sock, Traefik will automatically listen all the container on this socket
            - /var/run/docker.sock:/var/run/docker.sock

    app1:
        # whoami will list the IP address of this container
        image: containous/whoami
        labels: 
            # Treafik will be entertain this container by setting it to true
            traefik.enable: true
            # web entrypoint is set for this container, It will listen on port 9090 as this port is mapped to traefik port 80.
            traefik.http.routers.app1.entrypoints: web
            # Traefik will redirect all traffic to this container when request with following url is received.
            traefik.http.routers.app1.rule: Host(`app1.net`)

    app2:
        image: containous/whoami
        labels: 
            traefik.enable: true
            traefik.http.routers.app2.entrypoints: web
            traefik.http.routers.app2.rule: Host(`app2.net`)
